name:                wordle-game
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- hspec
- gtk3
- random >= 1.2.1.2
- directory >= 1.3.8.5

library:
  source-dirs:
    - src
  exposed-modules:
    - GameLogic

executables:
  wordle-game-exe:
    main: Main.hs
    source-dirs:
      - app
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -package directory
    dependencies:
      - wordle-game

tests:
  wordle-game-test:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wordle-game
      - hspec
    