name:                wordle-game
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- hspec

library:
  source-dirs: src

executables:
  wordle-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordle-game

tests:
  wordle-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordle-game
    - tasty
    - tasty-hunit
